# Generated by Django 5.0.2 on 2024-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0003_viberegister_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('phno', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'musicregister_table',
            },
        ),
        migrations.DeleteModel(
            name='VibeRegister',
        ),
        migrations.AlterField(
            model_name='vibeadmin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
