# Generated by Django 5.0.2 on 2024-02-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0007_rename_packages_vibepackages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vibepackages',
            old_name='musicpackage',
            new_name='musicPackage',
        ),
        migrations.AlterModelTable(
            name='register',
            table='musicviberegister_table',
        ),
        migrations.AlterModelTable(
            name='vibepackages',
            table='Package_table',
        ),
    ]
