# Generated by Django 5.0.3 on 2024-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('phno', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'musicviberegister_table',
            },
        ),
        migrations.CreateModel(
            name='VibeAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'musicapitable',
            },
        ),
        migrations.CreateModel(
            name='VibePackages',
            fields=[
                ('musicid', models.AutoField(primary_key=True, serialize=False)),
                ('musiccode', models.CharField(max_length=10)),
                ('musictitle', models.CharField(max_length=30)),
                ('musicPackage', models.CharField(max_length=30)),
                ('musicdescription', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'Package_table',
            },
        ),
    ]
