# Generated by Django 5.0.2 on 2024-02-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0004_register_delete_viberegister_alter_vibeadmin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('musicid', models.AutoField(primary_key=True, serialize=False)),
                ('musiccode', models.CharField(max_length=10)),
                ('musictitle', models.CharField(max_length=30)),
                ('musicgenre', models.CharField(max_length=30)),
                ('musicdescription', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'package_table',
            },
        ),
    ]
