# Generated by Django 5.0.2 on 2024-02-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0005_packages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='musicgenre',
            new_name='musicpackage',
        ),
    ]
