# Generated by Django 5.0.2 on 2024-02-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0006_rename_musicgenre_packages_musicpackage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='VibePackages',
        ),
    ]
