# Generated by Django 5.0.2 on 2024-02-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0008_rename_musicpackage_vibepackages_musicpackage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VibePackages',
        ),
    ]
